version: '1.0'

networks:
  mynetwork:
    driver: bridge

services:
  frontend:
    container_name: frontend
    image: reacttypescript:latest
    environment:
      - REACT_APP_BASE_URL = http://85.215.44.97:80
    networks:
      - mynetwork
    ports: 
      - "3000:3000"
    depends_on:
      - postgres
      - backend
  backend:
    container_name: backend
    image: romano2001/simple-dotnet-api:latest
    depends_on:
      - postgres
    networks:
      - mynetwork
    ports:
      - "80:80"
  postgres:
    container_name: postgres
    image: romano2001/postgres-db-test:latest
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    

